version: '3.8'
services:
  sql-server-db:
    container_name: mssqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1453:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Strongpassword123
      - MSSQL_PID=Express
      - MSSQL_USER=mayliba
      - MSSQL_PASSWORD=Strongpassword123
      - MSSQL_DATABASE=DBlabReport